### ISSUE TITLE
Add zh-CN

### ISSUE THREAD

**Issue by Xyyaua** [Mantan21/HSR-Warp-Simulator#13]
Add zh-CN file
[zh-cn.zip](https://github.com/Mantan21/HSR-Warp-Simulator/files/13802063/zh-cn.zip)
I have no any more time to merge and pull request this new language file.

by the way, why there no text for phonograph music etc.?

**Comment by AguzzTN54** [comment]
Thank you for your work, friend. I'll add it to the main app right away. And for now, I haven't added localization for phonograph tracks; maybe I'll add it later.
